require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'docker/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'db/seeds/*'
    - 'db/seeds.rb'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'spec/factories/**/*'

#
# Style
#
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

#
# Layout
#
Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

