version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - 23000:3000
    volumes:
      - .:/app
    command: ./bin/rails s -p 3000 -b 0.0.0.0
    depends_on:
      - db
  db:
    image: mysql:8.0.27
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
volumes:
  db_data:
    driver: local
