openapi: 3.0.0
info:
  title: Aravica api v1
  version: '1.0'
  description: Aravica api definitions called from frontend
servers:
  - description: development
    url: 'http://localhost:33000/api/v1'
paths:
  /user/user_registrations:
    $ref: ./paths/user/user_registrations/create.yml
  /common/origin_countries:
    $ref: ./paths/common/origin_countries/list.yml
components:
  schemas:
    $ref: ./schemas.yml
  responses:
    $ref: ./responses.yml
tags:
  - name: common
  - name: user
