openapi: 3.0.0
info:
  title: Aravica api v1
  version: '1.0'
  description: Aravica api definitions called from frontend
servers:
  - description: development
    url: 'http://localhost:33000/api/v1'
paths:
  /common/origin_countries:
    $ref: ./common/paths/origin_countries/list.yml
components:
  responses:
    $ref: ./responses.yml
