/* tslint:disable */
/* eslint-disable */
/**
 * Aravica api v1
 * Aravica api definitions called from frontend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateUserRegistrationsResponse
 */
export interface CreateUserRegistrationsResponse {
    /**
     * 
     * @type {number}
     * @memberof CreateUserRegistrationsResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof CreateUserRegistrationsResponse
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserRegistrationsResponse
     */
    provider: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserRegistrationsResponse
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserRegistrationsResponse
     */
    updatedAt: string;
}


