/* tslint:disable */
/* eslint-disable */
/**
 * Aravica api v1
 * Aravica api definitions called from frontend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
    /**
     * 
     * @type {object}
     * @memberof ErrorResponse
     */
    messages: object;
    /**
     * 
     * @type {Array<string>}
     * @memberof ErrorResponse
     */
    fullMessages: Array<string>;
}


