/* tslint:disable */
/* eslint-disable */
/**
 * Aravica api v1
 * Aravica api definitions called from frontend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CreateUserRegistrationsRequest } from '../models';
// @ts-ignore
import { CreateUserRegistrationsResponse } from '../models';
// @ts-ignore
import { ErrorResponse } from '../models';
/**
 * UserApi - axios parameter creator
 * @export
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create user registrations
         * @summary Create user registrations
         * @param {CreateUserRegistrationsRequest} createUserRegistrationsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUserRegistrations: async (createUserRegistrationsRequest: CreateUserRegistrationsRequest, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'createUserRegistrationsRequest' is not null or undefined
            assertParamExists('createUserRegistrations', 'createUserRegistrationsRequest', createUserRegistrationsRequest)
            const localVarPath = `/user/user_registrations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter, options.query);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createUserRegistrationsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 * @export
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * Create user registrations
         * @summary Create user registrations
         * @param {CreateUserRegistrationsRequest} createUserRegistrationsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createUserRegistrations(createUserRegistrationsRequest: CreateUserRegistrationsRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateUserRegistrationsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createUserRegistrations(createUserRegistrationsRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * UserApi - factory interface
 * @export
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * Create user registrations
         * @summary Create user registrations
         * @param {CreateUserRegistrationsRequest} createUserRegistrationsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUserRegistrations(createUserRegistrationsRequest: CreateUserRegistrationsRequest, options?: any): AxiosPromise<CreateUserRegistrationsResponse> {
            return localVarFp.createUserRegistrations(createUserRegistrationsRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserApi - object-oriented interface
 * @export
 * @class UserApi
 * @extends {BaseAPI}
 */
export class UserApi extends BaseAPI {
    /**
     * Create user registrations
     * @summary Create user registrations
     * @param {CreateUserRegistrationsRequest} createUserRegistrationsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public createUserRegistrations(createUserRegistrationsRequest: CreateUserRegistrationsRequest, options?: any) {
        return UserApiFp(this.configuration).createUserRegistrations(createUserRegistrationsRequest, options).then((request) => request(this.axios, this.basePath));
    }
}
