name: aravica-web ci
on: [pull_request]
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: checkout codes
        uses: actions/checkout@v2
      - name: cache docker image
        uses: actions/cache@v2
        id: cache-docker-image
        env:
          cache-name: docker-image
        with:
          path: ~/docker_images
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('docker/api/Dockerfile', 'Gemfile.lock') }}
      - name: create docker image
        if: steps.cache-docker-image.outputs.cache-hit != 'true'
        run: make build
      - name: save docker image
        if: steps.cache-docker-image.outputs.cache-hit != 'true'
        run: mkdir -p ~/docker_images && docker save aravica-web_api:latest > ~/docker_images/aravica-web_api_latest.tar
  api_lint_and_test:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: checkout codes
        uses: actions/checkout@v2
#      - name: setup ruby
#        uses: ruby/setup-ruby@v1
#        with:
#          ruby-version: 3.0.2
#          bundler-cache: true
      - name: load docker image
        run: docker load < ~/docker_images/aravica-web_api_latest.tar
      - name: run rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          github_token: ${{ secrets.github_token }}
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile rubocop-rspec:gemfile
          reporter: github-pr-review
          fail_on_error: true
      - name: run rspec
        run: make rspec
